openapi: 3.0.0
info:
  description: |
    This is the documentation for the SENG3011 API for the CalmClams group.
  version: "1.0.0"
  title: SENG3011 - CalmClams
servers:
  - url: 'http://calmclams.appspot.com/'
    description: CalmClams API
  - url: https://virtserver.swaggerhub.com/SMEZ1234/SENG3011-CalmClams/1.0.0
    description: SwaggerHub API Auto Mocking
tags:
  - name: API endpoint
    description: Endpoint for accessing disease report data through the API.
paths:
  "/disease_reports":
    get:
      tags:
        - API endpoint
      summary: Search database
      operationId: searchDiseaseRecords
      parameters:
        - name: start_date
          in: query
          description: The earliest date for which records will be searched.
          required: true
          schema:
            $ref: '#/components/schemas/Date-Query'
        - name: end_date
          in: query
          description: The latest date for which records will be searched.
          required: true
          schema:
            $ref: '#/components/schemas/Date-Query'
        - name: key_terms
          in: query
          description: A comma-separated sequence of terms to search records for. If omitted, all valid records will be returned.
          required: false
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: location
          in: query
          description: The location for which records will be searched.
          required: true
          schema:
            type: string
            example: Wuhan, Hubei Province
      responses:
        '200':
          description: Valid result(s) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/API-Response'
        '400':
          description: Issue with parameter.
        '404':
          description: No data matching parameter found.
        '405':
          description: Request method not allowed.
        '500':
          description: API encountered an error processing the request.
components:
  schemas:
    Article:
      type: object
      description: A single news article or report describing an occurrence of a disease and/or syndrome.
      properties:
        url:
          type: string
          description: The url of the article.
          example: https://www.who.int/csr/don/17-january-2020-novel-coronavirus-japan-exchina/en/
        date_of_publication:
          $ref: '#/components/schemas/Date-Exact'
        headline:
          type: string
          description: The headline of the article.
          example: Novel Coronavirus – Japan (ex-China)
        main_text:
          type: string
          description: The main body of the article text.
        reports:
          type: array
          description: A non-empty list of reports, with one report per separate case mentioned in the same article.
          items:
            $ref: '#/components/schemas/Report'
      required:
        - url
        - date_of_publication
        - headline
        - main_text
        - reports
    Report:
      type: object
      properties:
        diseases:
          type: array
          description: A list of possible/confirmed diseases for the case. Empty if the report lists only syndromes.
          items:
            $ref: '#/components/schemas/Disease'
        syndromes:
          type: array
          description: A list of syndromes exhibited for the case. Empty if the report lists only diseases.
          items:
            $ref: '#/components/schemas/Syndrome'
        event_date:
          $ref: '#/components/schemas/Date'
        locations:
          type: array
          description: A non-empty list of locations mentioned in the article for this case.
          items:
            $ref: '#/components/schemas/Location'
      required:
        - diseases
        - syndromes
        - event_date
        - locations
    Date:
      description: Either a single date or range of dates.
      anyOf:
        - $ref: '#/components/schemas/Date-Exact'
        - $ref: '#/components/schemas/Date-Range'
    Date-Exact:
      type: string
      description: A date in yyyy-MM-dd HH:mm:ss format. Segments other than the year may be replaced by 'x' for unknown values.
      pattern: '^(\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx)$'
      example: '2015-02-15 08:45:10'
    Date-Range:
      type: string
      description: A date range described in the form "<start_date> to <end_date>", where the two dates have the form described in the Date-Exact schema. The start date must be before the end date. If the 'x' wildcard is used for either dates, all possible dates matched by the start date must be before all possible dates matched by the end date.
      pattern: '^(\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx) to (\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx)$'
      example: '2015-02-15 08:45:10 to 2015-11-01 19:37:12'
    Date-Query:
      type: string
      description: "A date in yyyy-MM-ddTHH:mm:ss format. Segments other than the year may be replaced by 'x' to match all values. Note that unlike the Date-Exact schema, Date-Queries have a 'T' separating the date and time rather than a space (see the requirements for details: https://webcms3.cse.unsw.edu.au/static/uploads/course/SENG3011/20T1/4549c6fabd3561b84ad0b29f05b0bb7a07e28a4b2153e6ad8300ca8971de5030/AnalyticsPlatformEpidemics_v_8_3.pdf)."
      pattern: '^(\d{4})-(\d\d|xx)-(\d\d|xx)T(\d\d|xx):(\d\d|xx):(\d\d|xx)$'
      example: '2015-02-15T08:45:10'
    Disease:
      type: string
      description: The name of a disease.
      enum:
        - "unknown"
        - "other"
        - "anthrax cutaneous"
        - "anthrax gastrointestinous"
        - "anthrax inhalation"
        - "botulism"
        - "brucellosis"
        - "chikungunya"
        - "cholera"
        - "cryptococcosis"
        - "cryptosporidiosis"
        - "crimean-congo haemorrhagic fever"
        - "dengue"
        - "diphteria"
        - "ebola haemorrhagic fever"
        - "ehec (e.coli)"
        - "enterovirus 71 infection"
        - "influenza a/h5n1"
        - "influenza a/h7n9"
        - "influenza a/h9n2"
        - "influenza a/h1n1"
        - "influenza a/h1n2"
        - "influenza a/h3n5"
        - "influenza a/h3n2"
        - "influenza a/h2n2"
        - "hand, foot and mouth disease"
        - "hantavirus"
        - "hepatitis a"
        - "hepatitis b"
        - "hepatitis c"
        - "hepatitis d"
        - "hepatitis e"
        - "histoplasmosis"
        - "hiv/aids"
        - "lassa fever"
        - "malaria"
        - "marburg virus disease"
        - "measles"
        - "mers-cov"
        - "mumps"
        - "nipah virus"
        - "norovirus infection"
        - "pertussis"
        - "plague"
        - "pneumococcus pneumonia"
        - "poliomyelitis"
        - "q fever"
        - "rabies"
        - "rift valley fever"
        - "rotavirus infection"
        - "rubella"
        - "salmonellosis"
        - "sars"
        - "shigellosis"
        - "smallpox"
        - "staphylococcal enterotoxin b"
        - "thypoid fever"
        - "tuberculosis"
        - "tularemia"
        - "vaccinia and cowpox"
        - "varicella"
        - "west nile virus"
        - "yellow fever"
        - "yersiniosis"
        - "zika"
        - "legionares"
        - "listeriosis"
        - "monkeypox"
        - "COVID-19"
    Syndrome:
      type: string
      description: The name of a syndrome.
      enum:
        - "Haemorrhagic Fever"
        - "Acute Flacid Paralysis"
        - "Acute gastroenteritis"
        - "Acute respiratory syndrome"
        - "Influenza-like illness"
        - "Acute fever and rash"
        - "Fever of unknown Origin"
        - "Encephalitis"
        - "Meningitis"
    Location:
      type: object
      description: Identifiers for a location.
      properties:
        country:
          type: string
          description: The country's name.
          example: China
        location:
          type: string
          description: Location details apart from the country, e.g. Province, city, etc.
          example: Wuhan, Hubei Province
        geonames_id:
          type: number
          description: The ID that represents this location in the geonames database.
          example: 1791247
        google_id:
          type: string
          description: The ID that represents this location in the Google Places database.
          example: ChIJb_KF3fiuLjQRECJYbKzJwjk
    API-Response:
      type: object
      description: Response from the API containing the results and logs for the request.
      properties:
        parameter:
          type: object
          properties:
            start_date:
              $ref: '#/components/schemas/Date-Query'
            end_date:
              $ref: '#/components/schemas/Date-Query'
            key_terms:
              type: array
              items:
                type: string
                example: Anthrax
            location:
              type: string
              example: Wuhan, Hubei Province
        user_log:
          type: object
          properties:
            accessed_time:
              $ref: '#/components/schemas/Date-Exact'
            data_source:
              type: string
              example: outbreaks.globalincidentmap.com
            team_name:
              type: string
              example: CalmClams
        articles:
          type: array
          items:
            $ref: '#/components/schemas/Article'
